### PR TITLE
Track modification times for ceremony locks and contributions

### PR DESCRIPTION
**Pull request by silasbw**

### CODE REVIEW

**Comment by silasbw** [comment]
Closes https://github.com/celo-org/snark-setup-coordinator/issues/23

**Comment by silasbw** [comment]
TODO: persist "last lock time" when saving a contribution

**Review by kobigurk — APPROVED** [review]
LGTM. Do you want to handle the TODO in this PR or a next one?

**Comment by silasbw** [comment]
I implemented the TODO in this PR.

**Pull request merged**
