### PR TITLE
Add plumbing for signatures from powersoftau

### PR DESCRIPTION
**Pull request by silasbw**

### CODE REVIEW

**Comment by kobigurk** [comment]
Nice, thanks, I can continue from here. In my mind the TODOs are:
- [ ] Load the new extra files and sign their content.
- [ ] Verify their signatures at the coordinator side before accepting contribution.

**Comment by silasbw** [comment]
OK.  Shall we merge this PR or do you want to keep it open?

Merging now will avoid some potential merge conflicts in the coordinator-client and it might be easier to review your TODOs if they're in a self-contained PR.

**Comment by kobigurk** [comment]
> OK. Shall we merge this PR or do you want to keep it open?
> 
> Merging now will avoid some potential merge conflicts in the coordinator-client and it might be easier to review your TODOs if they're in a self-contained PR.

Let's merge, I based my PR on this one anyway!

**Review by kobigurk — APPROVED** [review]

**Comment by kobigurk** [comment]
> Nice, thanks, I can continue from here. In my mind the TODOs are:
> 
> * [ ]  Load the new extra files and sign their content.
> * [ ]  Verify their signatures at the coordinator side before accepting contribution.

Handled in https://github.com/celo-org/snark-setup-coordinator/pull/34.

**Pull request merged**
